### ISSUE TITLE
build fails on master

### ISSUE THREAD

**Issue by giogonzo** [buildo/showroom#1]
## description
with `yarn` and `yarn deploy` on master I get a bunch of errors like
```
Module build failed: Error: Cannot find module 'babel-core'
```

## how to reproduce
- {optional: describe steps to reproduce bug}

## specs
{optional: describe a possible fix for this bug, if not obvious}

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
closed by fc90e75c294d996e997c02bb5129c2bb6a7b4000
